import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // This matches the 'sidebarId' we used in docusaurus.config.ts
  tutorialSidebar: [
    'intro', // This pulls docusaurus/docs/intro.md
    {
      type: 'category',
      label: 'Chapter 1',
      items: [
        'Chapter-1/introduction',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 2',
      items: [
        'Chapter-2/fundamentals',
        'Chapter-2/workspace',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 3',
      items: [
        'Chapter-3/basic',
        'Chapter-3/xacro',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 4',
      items: [
        'Chapter-4/pid',
        'Chapter-4/teleop',
      ],
    },
    {
      type: 'category',
      label: 'Docusaurus Tutorials',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorial-basics', 
        },
        {
          type: 'autogenerated',
          dirName: 'tutorial-extras',
        },
      ],
    },
  ],
};

export default sidebars;