import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // This tells Docusaurus to just look at your folders and build the menu for you
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;