import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
<<<<<<< HEAD
  // This automatically creates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // '.' means it will generate from the entire 'docs' folder
    },
  ],
=======
  // This tells Docusaurus to just look at your folders and build the menu for you
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
>>>>>>> 646602f5 (Finilized structure: unified backend and frontend/ebook)
};

export default sidebars;