import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // This automatically creates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // '.' means it will generate from the entire 'docs' folder
    },
  ],
};

export default sidebars;